### ISSUE TITLE
License compliance

### ISSUE THREAD

**Issue by smcameron** [TheOpenSpaceProgram/gas-planets#1]
I see you are distributing binaries for gaseous-giganticus, but do not distribute source. There is at least one problem with this. There is no guarantee the source you find in my repo will not have changed relative to the binaries you're distributing, and you make no mention of exactly which variant of the source was used to build those binaries.  As it happens, it hasn't changed, but I am actively working on Space Nerds In Space, so it is quite likely that at some point I will make some change to gaseous-giganticus. If that happens, you would then technically (and unintentionally, I'm sure) be in violation of the license.

You should probably just include the source and a Makefile to build it and then this problem disappears.

If you would like, I can submit a patch to do this.

**Comment by 190n** [comment]
I copied over all the source files it needs to build as well as the Makefile. I also removed the macOS binary because I think I might have made some modifications to get it to compile and I don't have a Mac nearby to redo it.

Is that sufficient?

**Comment by smcameron** [comment]
I would also apply the following patch so that "make clean" and "make" do the right thing, and it also removes build_info.h, as that file is generated.

Otherwise, seems fine.  Thanks.

[fixup-gas-planet-makefile-patch.txt](https://github.com/TheOpenSpaceProgram/gas-planets/files/1502705/fixup-gas-planet-makefile-patch.txt)

**Comment by 190n** [comment]
Cool, done.
